<?php
session_start();
require_once '../../db_connect.php';
require_once '../../email_sender.php';

// Check if user is logged in
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header('Location: login.php');
    exit;
}

// Set page variables for the header
$page_title = "License & Subscription Administration";
$page_description = "Manage license keys, AI subscriptions, and free subscription keys";

// Function to get all license keys with optional filters
function get_license_keys($search_filter = '', $date_from = '', $date_to = '')
{
    $db = get_db_connection();
    $licenses = [];

    $query = 'SELECT * FROM license_keys WHERE 1=1';
    $types = '';
    $params = [];

    if (!empty($search_filter)) {
        $query .= ' AND (email LIKE ? OR license_key LIKE ?)';
        $search_param = '%' . $search_filter . '%';
        $types .= 'ss';
        $params[] = $search_param;
        $params[] = $search_param;
    }

    if (!empty($date_from)) {
        $query .= ' AND DATE(created_at) >= ?';
        $types .= 's';
        $params[] = $date_from;
    }

    if (!empty($date_to)) {
        $query .= ' AND DATE(created_at) <= ?';
        $types .= 's';
        $params[] = $date_to;
    }

    $query .= ' ORDER BY created_at DESC';

    if (!empty($params)) {
        $stmt = $db->prepare($query);
        $stmt->bind_param($types, ...$params);
        $stmt->execute();
        $result = $stmt->get_result();

        while ($row = $result->fetch_assoc()) {
            $licenses[] = $row;
        }
    } else {
        $result = $db->query($query);

        while ($row = $result->fetch_assoc()) {
            $licenses[] = $row;
        }
    }

    return $licenses;
}

// Function to get AI subscriptions
function get_ai_subscriptions($search_filter = '')
{
    global $pdo;
    $subscriptions = [];

    try {
        $query = "
            SELECT s.*, u.username
            FROM ai_subscriptions s
            LEFT JOIN community_users u ON s.user_id = u.id
            WHERE 1=1
        ";
        $params = [];

        if (!empty($search_filter)) {
            $query .= " AND (s.email LIKE ? OR s.subscription_id LIKE ? OR u.username LIKE ?)";
            $search_param = '%' . $search_filter . '%';
            $params[] = $search_param;
            $params[] = $search_param;
            $params[] = $search_param;
        }

        $query .= " ORDER BY s.created_at DESC LIMIT 100";

        $stmt = $pdo->prepare($query);
        $stmt->execute($params);
        $subscriptions = $stmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (PDOException $e) {
        error_log("Error fetching AI subscriptions: " . $e->getMessage());
    }

    return $subscriptions;
}

// Function to get AI subscription keys (free/promo)
function get_ai_subscription_keys()
{
    global $pdo;
    $keys = [];

    try {
        $stmt = $pdo->query("
            SELECT k.*, u.username as redeemed_by_username
            FROM ai_subscription_keys k
            LEFT JOIN community_users u ON k.redeemed_by_user_id = u.id
            ORDER BY k.created_at DESC
        ");
        $keys = $stmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (PDOException $e) {
        error_log("Error fetching AI subscription keys: " . $e->getMessage());
    }

    return $keys;
}

// Function to generate AI subscription key
function generate_ai_subscription_key($email = null, $duration_months = 1, $notes = '')
{
    global $pdo;

    $key = 'AISUB-' . strtoupper(bin2hex(random_bytes(4))) . '-' . strtoupper(bin2hex(random_bytes(4)));

    try {
        $stmt = $pdo->prepare("
            INSERT INTO ai_subscription_keys (subscription_key, email, duration_months, notes)
            VALUES (?, ?, ?, ?)
        ");
        $stmt->execute([$key, $email ?: null, $duration_months, $notes ?: null]);
        return $key;
    } catch (PDOException $e) {
        error_log("Error generating AI subscription key: " . $e->getMessage());
        return false;
    }
}

// Get chart data - keys generated by date
function get_chart_data()
{
    $db = get_db_connection();
    $result = $db->query("SELECT date(created_at) as date, COUNT(*) as count FROM license_keys GROUP BY date(created_at) ORDER BY date");

    $data = [];
    while ($row = $result->fetch_assoc()) {
        $data[] = [
            'date' => $row['date'],
            'count' => $row['count']
        ];
    }

    return $data;
}

// Get chart data - AI subscriptions by date
function get_subscription_chart_data()
{
    global $pdo;
    $data = [];

    try {
        $stmt = $pdo->query("
            SELECT DATE(created_at) as date,
                   COUNT(*) as total,
                   SUM(CASE WHEN status = 'active' THEN 1 ELSE 0 END) as active
            FROM ai_subscriptions
            GROUP BY DATE(created_at)
            ORDER BY date
        ");
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (PDOException $e) {
        error_log("Error fetching subscription chart data: " . $e->getMessage());
    }

    return $data;
}

// Handle form submissions
$generated_key = '';
$generated_sub_key = '';
$email_status = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['generate_key'])) {
        require_once '../license_functions.php';

        $email = filter_var($_POST['email'], FILTER_VALIDATE_EMAIL);
        if ($email) {
            $generated_key = create_license_key($email);
            $email_status = send_license_email($email, $generated_key);

            $_SESSION['generated_key'] = $generated_key;
            $_SESSION['email_status'] = $email_status;
            $_SESSION['customer_email'] = $email;
            header('Location: index.php#premium-keys');
            exit;
        }
    } elseif (isset($_POST['generate_sub_key'])) {
        $email = !empty($_POST['sub_email']) ? filter_var($_POST['sub_email'], FILTER_VALIDATE_EMAIL) : null;
        $duration = intval($_POST['duration_months'] ?? 1);
        $notes = trim($_POST['notes'] ?? '');

        // Allow 0 for permanent, otherwise 1-24 months
        if ($duration < 0) $duration = 1;
        if ($duration > 24 && $duration !== 0) $duration = 24;

        $generated_sub_key = generate_ai_subscription_key($email ?: null, $duration, $notes);

        if ($generated_sub_key) {
            $_SESSION['generated_sub_key'] = $generated_sub_key;
            $_SESSION['sub_key_duration'] = $duration;
            $_SESSION['sub_key_email'] = $email ?: 'Any user';
            $_SESSION['message'] = "Free subscription key generated successfully!";
            $_SESSION['message_type'] = 'success';
        } else {
            $_SESSION['message'] = "Failed to generate subscription key.";
            $_SESSION['message_type'] = 'error';
        }
        header('Location: index.php#free-sub-keys');
        exit;
    } elseif (isset($_POST['bulk_action'])) {
        // Handle bulk actions for license keys
        $action = $_POST['bulk_action'];
        $key_ids = $_POST['selected_keys'] ?? [];

        if (!empty($key_ids)) {
            $db = get_db_connection();
            $count = count($key_ids);
            $placeholders = implode(',', array_fill(0, $count, '?'));

            if ($action === 'activate') {
                $stmt = $db->prepare("UPDATE license_keys SET activated = 1, activation_date = CURRENT_TIMESTAMP WHERE id IN ($placeholders)");
                $stmt->bind_param(str_repeat('i', $count), ...$key_ids);
                $stmt->execute();
                $_SESSION['message'] = "$count license key(s) activated successfully.";
                $_SESSION['message_type'] = 'success';
            } elseif ($action === 'deactivate') {
                $stmt = $db->prepare("UPDATE license_keys SET activated = 0, activation_date = NULL WHERE id IN ($placeholders)");
                $stmt->bind_param(str_repeat('i', $count), ...$key_ids);
                $stmt->execute();
                $_SESSION['message'] = "$count license key(s) deactivated successfully.";
                $_SESSION['message_type'] = 'success';
            } elseif ($action === 'delete') {
                $stmt = $db->prepare("DELETE FROM license_keys WHERE id IN ($placeholders)");
                $stmt->bind_param(str_repeat('i', $count), ...$key_ids);
                $stmt->execute();
                $_SESSION['message'] = "$count license key(s) deleted successfully.";
                $_SESSION['message_type'] = 'success';
            } elseif ($action === 'resend_email') {
                $stmt = $db->prepare("SELECT id, email, license_key FROM license_keys WHERE id IN ($placeholders)");
                $stmt->bind_param(str_repeat('i', $count), ...$key_ids);
                $stmt->execute();
                $result = $stmt->get_result();

                $success_count = 0;
                while ($row = $result->fetch_assoc()) {
                    if (send_license_email($row['email'], $row['license_key'])) {
                        $success_count++;
                    }
                }
                $_SESSION['message'] = "$success_count out of $count email(s) sent successfully.";
                $_SESSION['message_type'] = $success_count > 0 ? 'success' : 'error';
            }

            header('Location: index.php#premium-keys');
            exit;
        }
    } elseif (isset($_POST['bulk_sub_key_action'])) {
        // Handle bulk actions for subscription keys
        $action = $_POST['bulk_sub_key_action'];
        $key_ids = $_POST['selected_sub_keys'] ?? [];

        if (!empty($key_ids)) {
            $count = count($key_ids);
            $placeholders = implode(',', array_fill(0, $count, '?'));

            if ($action === 'delete') {
                try {
                    $stmt = $pdo->prepare("DELETE FROM ai_subscription_keys WHERE id IN ($placeholders) AND redeemed_at IS NULL");
                    $stmt->execute($key_ids);
                    $deleted = $stmt->rowCount();
                    if ($deleted > 0) {
                        $_SESSION['message'] = "$deleted subscription key(s) deleted successfully.";
                        $_SESSION['message_type'] = 'success';
                    } else {
                        $_SESSION['message'] = "No keys deleted. Keys may have been redeemed.";
                        $_SESSION['message_type'] = 'error';
                    }
                } catch (PDOException $e) {
                    $_SESSION['message'] = "Error deleting keys.";
                    $_SESSION['message_type'] = 'error';
                }
            }

            header('Location: index.php#free-sub-keys');
            exit;
        }
    } elseif (isset($_POST['bulk_subscription_action'])) {
        // Handle bulk actions for AI subscriptions (Give Credit)
        $action = $_POST['bulk_subscription_action'];
        $subscription_ids = $_POST['selected_subscriptions'] ?? [];
        $credit_amount = floatval($_POST['credit_amount'] ?? 0);
        $credit_note = trim($_POST['credit_note'] ?? '');

        if (!empty($subscription_ids) && $action === 'give_credit' && $credit_amount > 0) {
            $count = count($subscription_ids);
            $placeholders = implode(',', array_fill(0, $count, '?'));
            $success_count = 0;
            $email_success = 0;

            try {
                // Update credit_balance for selected subscriptions
                $stmt = $pdo->prepare("
                    UPDATE ai_subscriptions
                    SET credit_balance = credit_balance + ?
                    WHERE id IN ($placeholders)
                ");
                $params = array_merge([$credit_amount], $subscription_ids);
                $stmt->execute($params);
                $success_count = $stmt->rowCount();

                // Log the credit addition for debugging
                error_log("Bulk credit: Added \$$credit_amount to " . count($subscription_ids) . " subscriptions. IDs: " . implode(',', $subscription_ids) . ". Rows affected: $success_count");

                // Send emails to affected users and verify credit was saved
                $stmt = $pdo->prepare("
                    SELECT id, email, subscription_id, credit_balance
                    FROM ai_subscriptions
                    WHERE id IN ($placeholders)
                ");
                $stmt->execute($subscription_ids);
                $subscriptions = $stmt->fetchAll(PDO::FETCH_ASSOC);

                // Log the actual credit balances after update
                foreach ($subscriptions as $s) {
                    error_log("Bulk credit verify: Subscription {$s['subscription_id']} now has credit_balance = {$s['credit_balance']}");
                }

                foreach ($subscriptions as $sub) {
                    if (send_free_credit_email($sub['email'], $credit_amount, $credit_note, $sub['subscription_id'])) {
                        $email_success++;
                    }
                }

                $_SESSION['message'] = "\$$credit_amount credit added to $success_count subscription(s). $email_success email(s) sent.";
                $_SESSION['message_type'] = 'success';
            } catch (PDOException $e) {
                error_log("Error adding bulk credit: " . $e->getMessage());
                $_SESSION['message'] = "Error adding credit to subscriptions.";
                $_SESSION['message_type'] = 'error';
            }

            header('Location: index.php#ai-subscriptions');
            exit;
        } else {
            $_SESSION['message'] = "Please select subscriptions and enter a valid credit amount.";
            $_SESSION['message_type'] = 'error';
            header('Location: index.php#ai-subscriptions');
            exit;
        }
    }
}

// Check for session messages
if (isset($_SESSION['generated_key'])) {
    $generated_key = $_SESSION['generated_key'];
    unset($_SESSION['generated_key']);
}
if (isset($_SESSION['generated_sub_key'])) {
    $generated_sub_key = $_SESSION['generated_sub_key'];
    unset($_SESSION['generated_sub_key']);
}
if (isset($_SESSION['email_status'])) {
    $email_status = $_SESSION['email_status'];
    unset($_SESSION['email_status']);
}
$customer_email = $_SESSION['customer_email'] ?? '';
unset($_SESSION['customer_email']);
$sub_key_duration = $_SESSION['sub_key_duration'] ?? 0;
unset($_SESSION['sub_key_duration']);
$sub_key_email = $_SESSION['sub_key_email'] ?? '';
unset($_SESSION['sub_key_email']);

// Get filter parameters
$search = isset($_GET['search']) ? trim($_GET['search']) : '';
$sub_search = isset($_GET['sub_search']) ? trim($_GET['sub_search']) : '';
$date_preset = isset($_GET['date_preset']) ? trim($_GET['date_preset']) : '';
$date_from = isset($_GET['date_from']) ? trim($_GET['date_from']) : '';
$date_to = isset($_GET['date_to']) ? trim($_GET['date_to']) : '';

// Calculate date range based on preset
if (!empty($date_preset) && $date_preset !== 'custom') {
    $date_to = date('Y-m-d');
    switch ($date_preset) {
        case 'today':
            $date_from = date('Y-m-d');
            break;
        case 'last_week':
            $date_from = date('Y-m-d', strtotime('-7 days'));
            break;
        case 'last_month':
            $date_from = date('Y-m-d', strtotime('-30 days'));
            break;
        case 'last_year':
            $date_from = date('Y-m-d', strtotime('-365 days'));
            break;
        case 'last_3_years':
            $date_from = date('Y-m-d', strtotime('-1095 days'));
            break;
        case 'last_5_years':
            $date_from = date('Y-m-d', strtotime('-1825 days'));
            break;
    }
}

// Get data
$licenses = get_license_keys($search, $date_from, $date_to);
$ai_subscriptions = get_ai_subscriptions($sub_search);
$ai_subscription_keys = get_ai_subscription_keys();
$chart_data = get_chart_data();
$subscription_chart_data = get_subscription_chart_data();

// Count stats
$db = get_db_connection();
$result = $db->query('SELECT COUNT(*) as count FROM community_users');
$row = $result->fetch_assoc();
$user_count = $row['count'] ?? 0;

$active_ai_subs = 0;
foreach ($ai_subscriptions as $sub) {
    if ($sub['status'] === 'active') $active_ai_subs++;
}

$unredeemed_keys = 0;
foreach ($ai_subscription_keys as $key) {
    if ($key['redeemed_at'] === null) $unredeemed_keys++;
}

// Flash messages
$message = '';
$message_type = '';
if (isset($_SESSION['message'])) {
    $message = $_SESSION['message'];
    $message_type = $_SESSION['message_type'];
    unset($_SESSION['message']);
    unset($_SESSION['message_type']);
}

include '../admin_header.php';
?>

<link rel="stylesheet" href="../search.css">
<link rel="stylesheet" href="../../resources/styles/checkbox.css">

<style>
    .section-tabs {
        display: flex;
        gap: 10px;
        margin-bottom: 30px;
        border-bottom: 2px solid #e5e7eb;
        padding-bottom: 0;
    }
    .section-tab {
        padding: 12px 24px;
        background: none;
        border: none;
        cursor: pointer;
        font-size: 1rem;
        font-weight: 500;
        color: #6b7280;
        border-bottom: 3px solid transparent;
        margin-bottom: -2px;
        transition: all 0.2s;
    }
    .section-tab:hover {
        color: #374151;
    }
    .section-tab.active {
        color: var(--primary-blue);
        border-bottom-color: var(--primary-blue);
    }
    .tab-content {
        display: none;
    }
    .tab-content.active {
        display: block;
    }
    .generate-form-grid {
        display: grid;
        grid-template-columns: 1fr 120px 1fr auto;
        gap: 15px;
        align-items: end;
    }
    @media (max-width: 800px) {
        .generate-form-grid {
            grid-template-columns: 1fr;
        }
    }
    .form-group label {
        display: block;
        margin-bottom: 5px;
        font-weight: 500;
        color: #374151;
    }
    .form-group input, .form-group select, .form-group textarea {
        width: 100%;
        padding: 10px 12px;
        border: 1px solid #d1d5db;
        border-radius: 6px;
        font-size: 0.95rem;
    }
    .form-group textarea {
        resize: vertical;
        min-height: 60px;
        box-sizing: border-box;
    }
    .key-display {
        background: #f0fdf4;
        border: 1px solid #86efac;
        border-radius: 8px;
        padding: 15px;
        margin: 15px 0;
    }
    .key-display code {
        font-size: 1.1rem;
        font-weight: bold;
        color: #166534;
    }
    .badge-free {
        background: #ede9fe;
        color: #7c3aed;
    }
    .badge-redeemed {
        background: #dbeafe;
        color: #1e40af;
    }
    .badge-active {
        background: #d1fae5;
        color: #065f46;
    }
    .badge-cancelled {
        background: #fee2e2;
        color: #991b1b;
    }
    .badge-expired {
        background: #f3f4f6;
        color: #6b7280;
    }
    .btn-purple {
        background: #8b5cf6;
        color: white;
        border: none;
    }
    .btn-purple:hover {
        background: #7c3aed;
    }
    .btn-purple:disabled {
        background: #c4b5fd;
        cursor: not-allowed;
    }
    .btn-secondary {
        background: #f3f4f6;
        color: #374151;
        border: 1px solid #d1d5db;
    }
    .btn-secondary:hover {
        background: #e5e7eb;
    }
    /* Modal Styles */
    .modal-overlay {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
        animation: fadeIn 0.2s ease;
    }
    @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
    }
    .modal-content {
        background: white;
        border-radius: 12px;
        width: 100%;
        max-width: 450px;
        margin: 20px;
        box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
        animation: slideUp 0.3s ease;
    }
    @keyframes slideUp {
        from { transform: translateY(20px); opacity: 0; }
        to { transform: translateY(0); opacity: 1; }
    }
    .modal-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px 24px;
        border-bottom: 1px solid #e5e7eb;
    }
    .modal-header h3 {
        margin: 0;
        font-size: 1.25rem;
        color: #111827;
    }
    .modal-close {
        background: none;
        border: none;
        font-size: 1.5rem;
        color: #9ca3af;
        cursor: pointer;
        padding: 0;
        line-height: 1;
    }
    .modal-close:hover {
        color: #374151;
    }
    .modal-body {
        padding: 24px;
    }
    .modal-body p {
        margin: 0 0 20px 0;
        color: #4b5563;
    }
    .modal-body .form-group {
        margin-bottom: 20px;
    }
    .modal-body .form-group:last-of-type {
        margin-bottom: 15px;
    }
    .modal-note {
        font-size: 0.875rem;
        color: #6b7280;
        background: #f3f4f6;
        padding: 12px;
        border-radius: 6px;
        margin-bottom: 0 !important;
    }
    .modal-footer {
        display: flex;
        justify-content: flex-end;
        gap: 12px;
        padding: 16px 24px;
        border-top: 1px solid #e5e7eb;
        background: #f9fafb;
        border-radius: 0 0 12px 12px;
    }
    .modal-footer .btn {
        padding: 10px 20px;
    }
</style>

<script>
    const chartData = <?php echo json_encode($chart_data); ?>;
    const subscriptionChartData = <?php echo json_encode($subscription_chart_data); ?>;
</script>
<script src="main.js"></script>

<div class="container">
    <!-- Section Tabs -->
    <div class="section-tabs">
        <button class="section-tab active" data-tab="premium-keys">Premium Licenses</button>
        <button class="section-tab" data-tab="ai-subscriptions">AI Subscriptions</button>
        <button class="section-tab" data-tab="free-sub-keys">Free AI Subscription Keys</button>
    </div>

    <?php if (!empty($message)): ?>
        <div class="<?php echo $message_type === 'success' ? 'success-message' : 'error-message'; ?>">
            <?php echo htmlspecialchars($message); ?>
        </div>
    <?php endif; ?>

    <!-- Premium License Keys Tab -->
    <div id="premium-keys" class="tab-content active">
        <!-- Statistics Cards -->
        <div class="stats-grid">
            <div class="stat-card">
                <h3>Total License Keys</h3>
                <div class="stat-value"><?php echo count($licenses); ?></div>
            </div>
            <div class="stat-card">
                <h3>Active Keys</h3>
                <div class="stat-value">
                    <?php
                    $active_count = 0;
                    foreach ($licenses as $license) {
                        if ($license['activated']) $active_count++;
                    }
                    echo $active_count;
                    ?>
                </div>
            </div>
            <div class="stat-card">
                <h3>Pending Keys</h3>
                <div class="stat-value">
                    <?php echo count($licenses) - $active_count; ?>
                </div>
            </div>
            <div class="stat-card">
                <h3>Registered Users</h3>
                <div class="stat-value"><?php echo $user_count; ?></div>
            </div>
        </div>

        <!-- Chart -->
        <div class="chart-container">
            <h2>License Keys Generated Over Time</h2>
            <canvas id="keysChart"></canvas>
        </div>

        <!-- Key Generation Form -->
        <div class="table-container">
            <h2>Generate New License Key</h2>

            <?php if ($generated_key): ?>
                <div class="success-message">
                    <strong>License key generated successfully!</strong><br>
                    Key: <span class="generated-key"><?php echo htmlspecialchars($generated_key); ?></span><br>
                    Email: <?php echo htmlspecialchars($customer_email); ?>
                </div>
                <?php if ($email_status !== null): ?>
                    <?php if ($email_status): ?>
                        <div class="success-message">Email sent to <?php echo htmlspecialchars($customer_email); ?></div>
                    <?php else: ?>
                        <div class="error-message">Failed to send email to <?php echo htmlspecialchars($customer_email); ?></div>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>

            <form method="post">
                <div class="form-group">
                    <label for="email">Customer Email:</label>
                    <div class="input-button-wrapper">
                        <input type="email" id="email" name="email" placeholder="customer@example.com" required>
                        <button type="submit" name="generate_key" class="btn btn-blue">Generate Key</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="table-container">
            <h2>License Keys</h2>

            <!-- Filter Container -->
            <form method="get" action="index.php" id="filter-form">
                <div class="filter-container">
                    <div class="filter-group search-group">
                        <label for="search">Search</label>
                        <input type="text" id="search" name="search" placeholder="Email or license key..." value="<?php echo htmlspecialchars($search); ?>">
                    </div>

                    <div class="filter-group date-filter-group">
                        <label for="date_preset">Date Range</label>
                        <select id="date_preset" name="date_preset" class="date-preset-select">
                            <option value="" <?php echo empty($date_preset) ? 'selected' : ''; ?>>All Time</option>
                            <option value="today" <?php echo $date_preset === 'today' ? 'selected' : ''; ?>>Today</option>
                            <option value="last_week" <?php echo $date_preset === 'last_week' ? 'selected' : ''; ?>>Last 7 Days</option>
                            <option value="last_month" <?php echo $date_preset === 'last_month' ? 'selected' : ''; ?>>Last 30 Days</option>
                            <option value="last_year" <?php echo $date_preset === 'last_year' ? 'selected' : ''; ?>>Last Year</option>
                            <option value="custom" <?php echo $date_preset === 'custom' ? 'selected' : ''; ?>>Custom Range</option>
                        </select>

                        <div class="custom-date-range" id="custom_date_range" style="display: <?php echo $date_preset === 'custom' ? 'flex' : 'none'; ?>;">
                            <div class="date-input-group">
                                <label for="date_from">From</label>
                                <input type="date" id="date_from" name="date_from" value="<?php echo $date_preset === 'custom' ? htmlspecialchars($date_from) : ''; ?>">
                            </div>
                            <div class="date-input-group">
                                <label for="date_to">To</label>
                                <input type="date" id="date_to" name="date_to" value="<?php echo $date_preset === 'custom' ? htmlspecialchars($date_to) : ''; ?>">
                            </div>
                        </div>
                    </div>

                    <div class="filter-actions">
                        <button type="submit" class="btn btn-blue">Apply</button>
                    </div>
                </div>
            </form>

            <!-- Bulk Actions -->
            <div class="bulk-actions-container">
                <div class="selection-info">
                    <span id="selected-count">0</span> selected
                </div>
                <div class="bulk-buttons">
                    <button type="button" class="btn btn-bulk btn-email" data-action="resend_email" disabled>
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z" />
                        </svg>
                        Send Email
                    </button>
                    <button type="button" class="btn btn-bulk btn-activate" data-action="activate" disabled>Activate</button>
                    <button type="button" class="btn btn-bulk btn-deactivate" data-action="deactivate" disabled>Deactivate</button>
                    <button type="button" class="btn btn-bulk btn-delete" data-action="delete" disabled>Delete</button>
                </div>
            </div>

            <?php if (empty($licenses)): ?>
                <p>No license keys found.</p>
            <?php else: ?>
                <form id="bulk-form" method="post">
                    <input type="hidden" name="bulk_action" id="bulk_action_input">
                    <div class="table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th class="checkbox-column">
                                        <div class="checkbox">
                                            <input type="checkbox" id="select-all">
                                            <label for="select-all"></label>
                                        </div>
                                    </th>
                                    <th>License Key</th>
                                    <th>Email</th>
                                    <th>Created</th>
                                    <th>Status</th>
                                    <th>Activation Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($licenses as $license): ?>
                                    <tr>
                                        <td class="checkbox-column">
                                            <div class="checkbox">
                                                <input type="checkbox" name="selected_keys[]" value="<?php echo $license['id']; ?>" class="row-checkbox" id="key-<?php echo $license['id']; ?>">
                                                <label for="key-<?php echo $license['id']; ?>"></label>
                                            </div>
                                        </td>
                                        <td class="key-field"><?php echo htmlspecialchars($license['license_key']); ?></td>
                                        <td><?php echo htmlspecialchars($license['email']); ?></td>
                                        <td><?php echo htmlspecialchars($license['created_at']); ?></td>
                                        <td>
                                            <?php if ($license['activated']): ?>
                                                <span class="badge badge-success">Active</span>
                                            <?php else: ?>
                                                <span class="badge badge-pending">Pending</span>
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo $license['activation_date'] ? htmlspecialchars($license['activation_date']) : 'N/A'; ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>

    <!-- AI Subscriptions Tab -->
    <div id="ai-subscriptions" class="tab-content">
        <div class="stats-grid">
            <div class="stat-card active">
                <h3>Active Subscriptions</h3>
                <div class="value"><?php echo $active_ai_subs; ?></div>
            </div>
            <div class="stat-card">
                <h3>Total Subscriptions</h3>
                <div class="value"><?php echo count($ai_subscriptions); ?></div>
            </div>
            <div class="stat-card free">
                <h3>Free Keys Available</h3>
                <div class="value"><?php echo $unredeemed_keys; ?></div>
            </div>
        </div>

        <!-- Subscription Chart -->
        <div class="chart-container">
            <h2>AI Subscriptions Over Time</h2>
            <canvas id="subscriptionsChart"></canvas>
        </div>

        <div class="table-container">
            <h2>AI Subscriptions</h2>

            <form method="get" action="index.php" style="margin-bottom: 20px;">
                <div class="input-button-wrapper">
                    <input type="text" name="sub_search" placeholder="Search by email, ID, or username..." value="<?php echo htmlspecialchars($sub_search); ?>">
                    <button type="submit" class="btn btn-blue">Search</button>
                </div>
            </form>

            <!-- Bulk Actions for AI Subscriptions -->
            <div class="bulk-actions-container" id="subscription-bulk-actions">
                <div class="selection-info">
                    <span id="subscription-selected-count">0</span> selected
                </div>
                <div class="bulk-buttons">
                    <button type="button" class="btn btn-bulk btn-purple" id="open-credit-modal" disabled>
                        Give Credit
                    </button>
                </div>
            </div>

            <?php if (empty($ai_subscriptions)): ?>
                <p>No AI subscriptions found.</p>
            <?php else: ?>
                <form id="subscription-bulk-form" method="post">
                    <input type="hidden" name="bulk_subscription_action" id="bulk_subscription_action_input" value="give_credit">
                    <input type="hidden" name="credit_amount" id="credit_amount_input">
                    <input type="hidden" name="credit_note" id="credit_note_input">
                    <div class="table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th class="checkbox-column">
                                        <div class="checkbox">
                                            <input type="checkbox" id="subscription-select-all">
                                            <label for="subscription-select-all"></label>
                                        </div>
                                    </th>
                                    <th>Subscription ID</th>
                                    <th>User</th>
                                    <th>Email</th>
                                    <th>Plan</th>
                                    <th>Status</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Credit</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($ai_subscriptions as $sub): ?>
                                    <tr>
                                        <td class="checkbox-column">
                                            <div class="checkbox">
                                                <input type="checkbox" name="selected_subscriptions[]" value="<?php echo $sub['id']; ?>" class="subscription-checkbox" id="sub-<?php echo $sub['id']; ?>">
                                                <label for="sub-<?php echo $sub['id']; ?>"></label>
                                            </div>
                                        </td>
                                        <td class="key-field"><?php echo htmlspecialchars($sub['subscription_id']); ?></td>
                                        <td><?php echo htmlspecialchars($sub['username'] ?? 'N/A'); ?></td>
                                        <td><?php echo htmlspecialchars($sub['email']); ?></td>
                                        <td><?php echo ucfirst($sub['billing_cycle']); ?> - $<?php echo number_format($sub['amount'], 2); ?></td>
                                        <td>
                                            <span class="badge badge-<?php echo $sub['status']; ?>">
                                                <?php echo ucfirst($sub['status']); ?>
                                            </span>
                                        </td>
                                        <td><?php echo date('M j, Y', strtotime($sub['start_date'])); ?></td>
                                        <td><?php echo date('M j, Y', strtotime($sub['end_date'])); ?></td>
                                        <td>$<?php echo number_format($sub['credit_balance'] ?? 0, 2); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>

    <!-- Credit Modal -->
    <div id="credit-modal" class="modal-overlay" style="display: none;">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Give Free Credit</h3>
                <button type="button" class="modal-close" id="close-credit-modal">&times;</button>
            </div>
            <div class="modal-body">
                <p>Add free credit to <strong><span id="modal-selected-count">0</span></strong> selected subscription(s).</p>
                <div class="form-group">
                    <label for="modal-credit-amount">Credit Amount ($)</label>
                    <input type="number" id="modal-credit-amount" min="0.01" step="0.01" placeholder="e.g., 5.00" required>
                </div>
                <div class="form-group">
                    <label for="modal-credit-note">Note (optional)</label>
                    <textarea id="modal-credit-note" rows="3" placeholder="e.g., Thank you for being a loyal customer!"></textarea>
                </div>
                <p class="modal-note">An email will be sent to each user notifying them of the free credit.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="cancel-credit-modal">Cancel</button>
                <button type="button" class="btn btn-purple" id="confirm-give-credit">Give Credit</button>
            </div>
        </div>
    </div>

    <!-- Free Subscription Keys Tab -->
    <div id="free-sub-keys" class="tab-content">
        <div class="stats-grid">
            <div class="stat-card free">
                <h3>Available Keys</h3>
                <div class="value"><?php echo $unredeemed_keys; ?></div>
            </div>
            <div class="stat-card pending">
                <h3>Redeemed Keys</h3>
                <div class="value"><?php echo count($ai_subscription_keys) - $unredeemed_keys; ?></div>
            </div>
            <div class="stat-card">
                <h3>Total Generated</h3>
                <div class="value"><?php echo count($ai_subscription_keys); ?></div>
            </div>
        </div>

        <div class="table-container">
            <h2>Generate Free Subscription Key</h2>
            <p style="color: #6b7280; margin-bottom: 20px;">Create keys that can be redeemed for free AI subscription access without payment.</p>

            <?php if ($generated_sub_key): ?>
                <div class="key-display">
                    <strong>Key Generated:</strong><br>
                    <code><?php echo htmlspecialchars($generated_sub_key); ?></code><br>
                    <small>Duration: <?php echo $sub_key_duration == 0 ? 'Permanent' : $sub_key_duration . ' month(s)'; ?> | For: <?php echo htmlspecialchars($sub_key_email); ?></small>
                </div>
            <?php endif; ?>

            <form method="post">
                <div class="generate-form-grid">
                    <div class="form-group">
                        <label for="sub_email">Restrict to Email (optional)</label>
                        <input type="email" id="sub_email" name="sub_email" placeholder="Leave empty for any user">
                    </div>
                    <div class="form-group">
                        <label for="duration_months">Duration</label>
                        <select id="duration_months" name="duration_months">
                            <option value="1">1 month</option>
                            <option value="3">3 months</option>
                            <option value="6">6 months</option>
                            <option value="12">12 months</option>
                            <option value="0">Permanent</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="notes">Notes (optional)</label>
                        <input type="text" id="notes" name="notes" placeholder="e.g., Giveaway winner">
                    </div>
                    <div class="form-group">
                        <button type="submit" name="generate_sub_key" class="btn btn-purple" style="margin-top: 24px;">Generate Key</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="table-container">
            <h2>Free Subscription Keys</h2>

            <!-- Bulk Actions for Subscription Keys -->
            <div class="bulk-actions-container" id="sub-key-bulk-actions">
                <div class="selection-info">
                    <span id="sub-key-selected-count">0</span> selected
                </div>
                <div class="bulk-buttons">
                    <button type="button" class="btn btn-bulk btn-delete" id="sub-key-bulk-delete" data-action="delete" disabled>Delete Selected</button>
                </div>
            </div>

            <?php if (empty($ai_subscription_keys)): ?>
                <p>No free subscription keys generated yet.</p>
            <?php else: ?>
                <form id="sub-key-bulk-form" method="post">
                    <input type="hidden" name="bulk_sub_key_action" id="bulk_sub_key_action_input">
                    <div class="table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th class="checkbox-column">
                                        <div class="checkbox">
                                            <input type="checkbox" id="sub-key-select-all">
                                            <label for="sub-key-select-all"></label>
                                        </div>
                                    </th>
                                    <th>Key</th>
                                    <th>Duration</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    <th>Created</th>
                                    <th>Redeemed By</th>
                                    <th>Notes</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($ai_subscription_keys as $key): ?>
                                    <tr class="<?php echo $key['redeemed_at'] ? 'redeemed-row' : ''; ?>">
                                        <td class="checkbox-column">
                                            <?php if (!$key['redeemed_at']): ?>
                                                <div class="checkbox">
                                                    <input type="checkbox" name="selected_sub_keys[]" value="<?php echo $key['id']; ?>" class="sub-key-checkbox" id="sub-key-<?php echo $key['id']; ?>">
                                                    <label for="sub-key-<?php echo $key['id']; ?>"></label>
                                                </div>
                                            <?php endif; ?>
                                        </td>
                                        <td class="key-field"><?php echo htmlspecialchars($key['subscription_key']); ?></td>
                                        <td><?php echo $key['duration_months'] == 0 ? '<span style="color:#8b5cf6;font-weight:500;">Permanent</span>' : $key['duration_months'] . ' month' . ($key['duration_months'] > 1 ? 's' : ''); ?></td>
                                        <td><?php echo $key['email'] ? htmlspecialchars($key['email']) : '<span style="color:#9ca3af;">Any user</span>'; ?></td>
                                        <td>
                                            <?php if ($key['redeemed_at']): ?>
                                                <span class="badge badge-redeemed">Redeemed</span>
                                            <?php else: ?>
                                                <span class="badge badge-free">Available</span>
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo date('M j, Y', strtotime($key['created_at'])); ?></td>
                                        <td>
                                            <?php if ($key['redeemed_by_username']): ?>
                                                <?php echo htmlspecialchars($key['redeemed_by_username']); ?>
                                                <br><small><?php echo date('M j, Y', strtotime($key['redeemed_at'])); ?></small>
                                            <?php else: ?>
                                                -
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo $key['notes'] ? htmlspecialchars($key['notes']) : '-'; ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Tab switching
    const tabs = document.querySelectorAll('.section-tab');
    const contents = document.querySelectorAll('.tab-content');

    // Check URL hash for active tab
    const hash = window.location.hash.substring(1);
    if (hash) {
        tabs.forEach(t => t.classList.remove('active'));
        contents.forEach(c => c.classList.remove('active'));

        const targetTab = document.querySelector(`[data-tab="${hash}"]`);
        const targetContent = document.getElementById(hash);
        if (targetTab && targetContent) {
            targetTab.classList.add('active');
            targetContent.classList.add('active');
        }
    }

    tabs.forEach(tab => {
        tab.addEventListener('click', function() {
            const target = this.dataset.tab;

            tabs.forEach(t => t.classList.remove('active'));
            contents.forEach(c => c.classList.remove('active'));

            this.classList.add('active');
            document.getElementById(target).classList.add('active');

            history.replaceState(null, null, '#' + target);
        });
    });

    // Subscription Key Bulk Selection
    const subKeySelectAll = document.getElementById('sub-key-select-all');
    const subKeyCheckboxes = document.querySelectorAll('.sub-key-checkbox');
    const subKeySelectedCount = document.getElementById('sub-key-selected-count');
    const subKeyBulkDelete = document.getElementById('sub-key-bulk-delete');
    const subKeyBulkForm = document.getElementById('sub-key-bulk-form');
    const subKeyBulkActionInput = document.getElementById('bulk_sub_key_action_input');

    function updateSubKeySelection() {
        const checked = document.querySelectorAll('.sub-key-checkbox:checked');
        const count = checked.length;
        subKeySelectedCount.textContent = count;
        subKeyBulkDelete.disabled = count === 0;
    }

    if (subKeySelectAll) {
        subKeySelectAll.addEventListener('change', function() {
            subKeyCheckboxes.forEach(cb => cb.checked = this.checked);
            updateSubKeySelection();
        });
    }

    subKeyCheckboxes.forEach(cb => {
        cb.addEventListener('change', function() {
            updateSubKeySelection();
            // Update select all checkbox state
            if (subKeySelectAll) {
                const allChecked = document.querySelectorAll('.sub-key-checkbox:checked').length === subKeyCheckboxes.length;
                subKeySelectAll.checked = allChecked && subKeyCheckboxes.length > 0;
            }
        });
    });

    if (subKeyBulkDelete) {
        subKeyBulkDelete.addEventListener('click', function() {
            const checked = document.querySelectorAll('.sub-key-checkbox:checked');
            if (checked.length === 0) return;

            if (confirm(`Are you sure you want to delete ${checked.length} subscription key(s)?`)) {
                subKeyBulkActionInput.value = 'delete';
                subKeyBulkForm.submit();
            }
        });
    }

    // AI Subscription Bulk Selection
    const subscriptionSelectAll = document.getElementById('subscription-select-all');
    const subscriptionCheckboxes = document.querySelectorAll('.subscription-checkbox');
    const subscriptionSelectedCount = document.getElementById('subscription-selected-count');
    const openCreditModalBtn = document.getElementById('open-credit-modal');
    const subscriptionBulkForm = document.getElementById('subscription-bulk-form');
    const creditAmountInput = document.getElementById('credit_amount_input');
    const creditNoteInput = document.getElementById('credit_note_input');

    // Modal elements
    const creditModal = document.getElementById('credit-modal');
    const closeCreditModalBtn = document.getElementById('close-credit-modal');
    const cancelCreditModalBtn = document.getElementById('cancel-credit-modal');
    const confirmGiveCreditBtn = document.getElementById('confirm-give-credit');
    const modalSelectedCount = document.getElementById('modal-selected-count');
    const modalCreditAmount = document.getElementById('modal-credit-amount');
    const modalCreditNote = document.getElementById('modal-credit-note');

    function updateSubscriptionSelection() {
        const checked = document.querySelectorAll('.subscription-checkbox:checked');
        const count = checked.length;
        subscriptionSelectedCount.textContent = count;
        if (openCreditModalBtn) {
            openCreditModalBtn.disabled = count === 0;
        }
    }

    if (subscriptionSelectAll) {
        subscriptionSelectAll.addEventListener('change', function() {
            subscriptionCheckboxes.forEach(cb => cb.checked = this.checked);
            updateSubscriptionSelection();
        });
    }

    subscriptionCheckboxes.forEach(cb => {
        cb.addEventListener('change', function() {
            updateSubscriptionSelection();
            // Update select all checkbox state
            if (subscriptionSelectAll) {
                const checkedCount = document.querySelectorAll('.subscription-checkbox:checked').length;
                const allChecked = checkedCount === subscriptionCheckboxes.length;
                subscriptionSelectAll.checked = allChecked && subscriptionCheckboxes.length > 0;
                subscriptionSelectAll.indeterminate = checkedCount > 0 && !allChecked;
            }
        });
    });

    // Modal functionality
    function openModal() {
        const count = document.querySelectorAll('.subscription-checkbox:checked').length;
        if (count === 0) return;
        modalSelectedCount.textContent = count;
        modalCreditAmount.value = '';
        modalCreditNote.value = '';
        creditModal.style.display = 'flex';
        modalCreditAmount.focus();
    }

    function closeModal() {
        creditModal.style.display = 'none';
    }

    if (openCreditModalBtn) {
        openCreditModalBtn.addEventListener('click', openModal);
    }

    if (closeCreditModalBtn) {
        closeCreditModalBtn.addEventListener('click', closeModal);
    }

    if (cancelCreditModalBtn) {
        cancelCreditModalBtn.addEventListener('click', closeModal);
    }

    // Close modal on overlay click
    if (creditModal) {
        creditModal.addEventListener('click', function(e) {
            if (e.target === creditModal) {
                closeModal();
            }
        });
    }

    // Close modal on Escape key
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && creditModal && creditModal.style.display === 'flex') {
            closeModal();
        }
    });

    // Confirm give credit
    if (confirmGiveCreditBtn) {
        confirmGiveCreditBtn.addEventListener('click', function() {
            const amount = parseFloat(modalCreditAmount.value);
            const note = modalCreditNote.value.trim();
            const checkedCount = document.querySelectorAll('.subscription-checkbox:checked').length;

            if (isNaN(amount) || amount <= 0) {
                alert('Please enter a valid credit amount greater than 0.');
                modalCreditAmount.focus();
                return;
            }

            if (confirm(`Are you sure you want to give $${amount.toFixed(2)} credit to ${checkedCount} subscription(s)?`)) {
                creditAmountInput.value = amount;
                creditNoteInput.value = note;
                subscriptionBulkForm.submit();
            }
        });
    }

    // Allow Enter key in credit amount field to submit
    if (modalCreditAmount) {
        modalCreditAmount.addEventListener('keydown', function(e) {
            if (e.key === 'Enter') {
                e.preventDefault();
                confirmGiveCreditBtn.click();
            }
        });
    }
});
</script>
