<?php
session_start();
require_once '../db_connect.php';

// Check if user is logged in
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header('Location: login.php');
    exit;
}

// Function to get all license keys with optional email filter
function get_license_keys($email_filter = '') {
    $db = get_db_connection();
    
    if (!empty($email_filter)) {
        $stmt = $db->prepare('SELECT * FROM license_keys WHERE email LIKE :email ORDER BY created_at DESC');
        $stmt->bindValue(':email', '%' . $email_filter . '%', SQLITE3_TEXT);
        $result = $stmt->execute();
    } else {
        $result = $db->query('SELECT * FROM license_keys ORDER BY created_at DESC');
    }
    
    $licenses = [];
    while ($row = $result->fetchArray(SQLITE3_ASSOC)) {
        $licenses[] = $row;
    }
    
    return $licenses;
}

// Get chart data - keys generated by date
function get_chart_data() {
    $db = get_db_connection();
    $result = $db->query("SELECT date(created_at) as date, COUNT(*) as count FROM license_keys GROUP BY date(created_at) ORDER BY date");
    
    $data = [];
    while ($row = $result->fetchArray(SQLITE3_ASSOC)) {
        $data[] = [
            'date' => $row['date'],
            'count' => $row['count']
        ];
    }
    
    return $data;
}

// Handle license key generation
$generated_key = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['generate_key'])) {
        require_once '../license_functions.php';
        
        $email = filter_var($_POST['email'], FILTER_VALIDATE_EMAIL);
        if ($email) {
            $generated_key = create_license_key($email);
            
            // Auto-activate the key
            $db = get_db_connection();
            $stmt = $db->prepare('UPDATE license_keys SET activated = 1, activation_date = CURRENT_TIMESTAMP WHERE license_key = :key');
            $stmt->bindValue(':key', $generated_key, SQLITE3_TEXT);
            $stmt->execute();
            
            // Store message in session and redirect to prevent form resubmission on refresh
            $_SESSION['generated_key'] = $generated_key;
            header('Location: index.php');
            exit;
        }
    } elseif (isset($_POST['activate_key'])) {
        // Handle activation
        $key_id = $_POST['key_id'];
        
        $db = get_db_connection();
        $stmt = $db->prepare('UPDATE license_keys SET activated = 1, activation_date = CURRENT_TIMESTAMP WHERE id = :id');
        $stmt->bindValue(':id', $key_id, SQLITE3_INTEGER);
        $stmt->execute();
        
        header('Location: index.php' . (isset($_GET['search']) ? '?search=' . urlencode($_GET['search']) : ''));
        exit;
    } elseif (isset($_POST['deactivate_key'])) {
        // Handle deactivation
        $key_id = $_POST['key_id'];
        
        $db = get_db_connection();
        $stmt = $db->prepare('UPDATE license_keys SET activated = 0, activation_date = NULL WHERE id = :id');
        $stmt->bindValue(':id', $key_id, SQLITE3_INTEGER);
        $stmt->execute();
        
        header('Location: index.php' . (isset($_GET['search']) ? '?search=' . urlencode($_GET['search']) : ''));
        exit;
    } elseif (isset($_POST['delete_key'])) {
        // Handle deletion
        $key_id = $_POST['key_id'];
        
        $db = get_db_connection();
        $stmt = $db->prepare('DELETE FROM license_keys WHERE id = :id');
        $stmt->bindValue(':id', $key_id, SQLITE3_INTEGER);
        $stmt->execute();
        
        header('Location: index.php' . (isset($_GET['search']) ? '?search=' . urlencode($_GET['search']) : ''));
        exit;
    }
}

// Check for message from previous submission
if (isset($_SESSION['generated_key'])) {
    $generated_key = $_SESSION['generated_key'];
    unset($_SESSION['generated_key']); // Clear the message
}

// Get search parameter
$search = isset($_GET['search']) ? trim($_GET['search']) : '';

// Get license keys (filtered by search if provided)
$licenses = get_license_keys($search);

// Get chart data
$chart_data = get_chart_data();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="../images/argo-logo/A-logo.ico">
    <title>Argo Sales Tracker - Admin</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            background-color: #f5f7fa;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 1px solid #e2e8f0;
        }
        h1 {
            color: #1e3a8a;
            margin: 0;
        }
        .btn {
            background: #2563eb;
            color: white;
            border: none;
            padding: 10px 15px;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            font-size: 14px;
        }
        .btn:hover {
            background: #1d4ed8;
        }
        .form-container, .chart-container, .search-container, .table-container {
            background: white;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }
        .chart-container {
            position: relative;
            height: 300px;
        }
        .chart-container h2 {
            margin-top: 0;
        }
        .stats-row {
            display: flex;
            gap: 20px;
            margin-bottom: 20px;
        }
        .stat-card {
            flex: 1;
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .stat-card h3 {
            margin-top: 0;
            color: #4b5563;
            font-size: 16px;
            font-weight: 500;
        }
        .stat-card .stat-value {
            font-size: 32px;
            font-weight: bold;
            color: #1e3a8a;
            margin: 10px 0;
        }
        .form-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 500;
        }
        input[type="email"], input[type="text"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #d1d5db;
            border-radius: 4px;
            box-sizing: border-box;
        }
        .search-container {
            display: flex;
            gap: 10px;
        }
        .search-container input {
            flex-grow: 1;
        }
        .search-container form {
            display: flex;
            width: 100%;
            gap: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        th {
            background-color: #f8fafc;
            font-weight: 600;
        }
        tr:hover {
            background-color: #f9fafb;
        }
        .key-field {
            font-family: monospace;
        }
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: 500;
        }
        .badge-success {
            background-color: #d1fae5;
            color: #065f46;
        }
        .badge-pending {
            background-color: #fef3c7;
            color: #92400e;
        }
        .generated-key {
            background: #ecfdf5;
            border: 1px solid #10b981;
            border-radius: 4px;
            padding: 15px;
            margin-bottom: 20px;
            font-family: monospace;
            font-size: 16px;
        }
        .logout-btn {
            background: #ef4444;
        }
        .logout-btn:hover {
            background: #dc2626;
        }
        .action-buttons {
            display: flex;
            gap: 5px;
        }
        .btn-small {
            padding: 5px 10px;
            font-size: 12px;
        }
        .btn-activate {
            background: #10b981;
        }
        .btn-activate:hover {
            background: #059669;
        }
        .btn-deactivate {
            background: #f59e0b;
        }
        .btn-deactivate:hover {
            background: #d97706;
        }
        .btn-delete {
            background: #ef4444;
        }
        .btn-delete:hover {
            background: #dc2626;
        }
        .search-results {
            margin-bottom: 15px;
            font-style: italic;
        }
        .table-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }
        .table-header h2 {
            margin: 0;
        }
        .total-keys {
            font-weight: bold;
            color: #1e3a8a;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>License Key Administration</h1>
            <a href="logout.php" class="btn logout-btn">Logout</a>
        </div>
        
        <!-- Statistics Cards -->
        <div class="stats-row">
            <div class="stat-card">
                <h3>Total License Keys</h3>
                <div class="stat-value"><?php echo count($licenses); ?></div>
            </div>
            <div class="stat-card">
                <h3>Active Keys</h3>
                <div class="stat-value"><?php 
                    $active_count = 0;
                    foreach ($licenses as $license) {
                        if ($license['activated']) {
                            $active_count++;
                        }
                    }
                    echo $active_count;
                ?></div>
            </div>
            <div class="stat-card">
                <h3>Pending Keys</h3>
                <div class="stat-value"><?php echo count($licenses) - $active_count; ?></div>
            </div>
        </div>
        
        <!-- Chart -->
        <div class="chart-container">
            <h2>License Keys Generated Over Time</h2>
            <canvas id="keysChart"></canvas>
        </div>
        
        <div class="form-container">
            <h2>Generate New License Key</h2>
            <?php if ($generated_key): ?>
                <div class="generated-key">
                    New key generated: <?php echo htmlspecialchars($generated_key); ?>
                </div>
            <?php endif; ?>
            
            <form method="post">
                <div class="form-group">
                    <label for="email">Customer Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <button type="submit" name="generate_key" class="btn">Generate License Key</button>
            </form>
        </div>
        
        <div class="search-container">
            <form method="get" action="index.php">
                <input type="text" name="search" placeholder="Search by email..." value="<?php echo htmlspecialchars($search); ?>">
                <button type="submit" class="btn">Search</button>
                <?php if (!empty($search)): ?>
                    <a href="index.php" class="btn" style="background: #6b7280;">Clear</a>
                <?php endif; ?>
            </form>
        </div>
        
        <div class="table-container">
            <div class="table-header">
                <h2>License Keys</h2>
                <span class="total-keys">Total: <?php echo count($licenses); ?></span>
            </div>
            
            <?php if (!empty($search)): ?>
                <div class="search-results">
                    Showing results for: "<?php echo htmlspecialchars($search); ?>" (<?php echo count($licenses); ?> results)
                </div>
            <?php endif; ?>
            
            <?php if (empty($licenses)): ?>
                <p>No license keys found.</p>
            <?php else: ?>
                <table>
                    <thead>
                        <tr>
                            <th>License Key</th>
                            <th>Email</th>
                            <th>Created</th>
                            <th>Status</th>
                            <th>Activation Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($licenses as $license): ?>
                            <tr>
                                <td class="key-field"><?php echo htmlspecialchars($license['license_key']); ?></td>
                                <td><?php echo htmlspecialchars($license['email']); ?></td>
                                <td><?php echo htmlspecialchars($license['created_at']); ?></td>
                                <td>
                                    <?php if ($license['activated']): ?>
                                        <span class="badge badge-success">Active</span>
                                    <?php else: ?>
                                        <span class="badge badge-pending">Pending</span>
                                    <?php endif; ?>
                                </td>
                                <td><?php echo $license['activation_date'] ? htmlspecialchars($license['activation_date']) : 'N/A'; ?></td>
                                <td class="action-buttons">
                                    <?php if (!$license['activated']): ?>
                                        <form method="post" onsubmit="return confirm('Are you sure you want to activate this license key?');">
                                            <input type="hidden" name="key_id" value="<?php echo htmlspecialchars($license['id']); ?>">
                                            <input type="hidden" name="key" value="<?php echo htmlspecialchars($license['license_key']); ?>">
                                            <button type="submit" name="activate_key" class="btn btn-small btn-activate">Activate</button>
                                        </form>
                                    <?php else: ?>
                                        <form method="post" onsubmit="return confirm('Are you sure you want to deactivate this license key?');">
                                            <input type="hidden" name="key_id" value="<?php echo htmlspecialchars($license['id']); ?>">
                                            <button type="submit" name="deactivate_key" class="btn btn-small btn-deactivate">Deactivate</button>
                                        </form>
                                    <?php endif; ?>
                                    <form method="post" onsubmit="return confirm('Are you sure you want to delete this license key? This action cannot be undone.');">
                                        <input type="hidden" name="key_id" value="<?php echo htmlspecialchars($license['id']); ?>">
                                        <button type="submit" name="delete_key" class="btn btn-small btn-delete">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </div>
    
    <script>
    // Chart initialization
    document.addEventListener('DOMContentLoaded', function() {
        const chartData = <?php echo json_encode($chart_data); ?>;
        const labels = chartData.map(item => item.date);
        const counts = chartData.map(item => item.count);
        
        const ctx = document.getElementById('keysChart').getContext('2d');
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'License Keys Generated',
                    data: counts,
                    backgroundColor: 'rgba(37, 99, 235, 0.2)',
                    borderColor: 'rgba(37, 99, 235, 1)',
                    borderWidth: 2,
                    tension: 0.3,
                    pointRadius: 4,
                    pointBackgroundColor: 'rgba(37, 99, 235, 1)'
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true,
                        ticks: {
                            precision: 0
                        }
                    },
                    x: {
                        ticks: {
                            padding: 10
                        }
                    }
                },
                plugins: {
                    title: {
                        display: false
                    },
                    legend: {
                        position: 'top',
                    }
                },
                layout: {
                    padding: {
                        bottom: 40
                    }
                }
            }
        });
    });
    </script>
</body>
</html>